#!/bin/sh
set -fu

case "${1-}" in
    '-h'|'--help')
        printf 'Usage: repo-update-includes\n'
        exit 0
    ;;
esac

includes_dir="${AENV_ROOT:?}/includes"

exec make \
    -C "${includes_dir}" \
    -f "${AENV_SKEL_SHAREDIR:?}/mk/includes.gnu.mk" \
    \
    AENV_SKEL_SHAREDIR="${AENV_SKEL_SHAREDIR:?}" \
    S="${includes_dir}" \
    O="${includes_dir}" \
    \
    "${@}"
